package com.onenation.recommender
import android.app.*; import android.content.Context; import android.content.Intent; import android.os.Build; import android.os.Handler; import android.os.IBinder; import android.os.Looper; import android.telephony.TelephonyManager; import java.text.SimpleDateFormat; import java.util.*
class RecommendationService : Service() {
    companion object { const val ACT_STOP = "com.onenation.recommender.STOP"; var isRunning = false; var successCount = 0; var totalAttempts = 0; var failedCount = 0; var installedCount = 0; var lastLog = ""; var onUpdate: (()->Unit)? = null }
    private val h = Handler(Looper.getMainLooper()); private var target = 100; private var today = 0; private val gen = mutableSetOf<String>()
    private val r = object : Runnable { override fun run() { if(!isRunning) return; target=getSharedPreferences("onenation_settings",Context.MODE_PRIVATE).getInt("daily_target",100); if(today>=target){ lastLog="Target reached"; onUpdate?.invoke(); stopS(); return }; var n: String; val due=ContactManager.getDueForRetry(this@RecommendationService); if(due.isNotEmpty()) n=due.first().phone else{ val p=ContactManager.getPending(this@RecommendationService).filter{it.nextRetryTime.isBlank()}; if(p.isNotEmpty()) n=p.first().phone else{ var g:String; do{g=NumberGenerator.generate()} while(gen.contains(g)||ContactManager.isPending(this@RecommendationService,g)||ContactManager.isInstalled(this@RecommendationService,g)); gen.add(g); ContactManager.incrementGeneratedCount(this@RecommendationService); n=g } }; proc(n); h.postDelayed(this,8000) } }
    override fun onCreate() { super.onCreate(); if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O) getSystemService(NotificationManager::class.java).createNotificationChannel(NotificationChannel("on","One Nation",NotificationManager.IMPORTANCE_LOW)) }
    override fun onStartCommand(i: Intent?, f: Int, s: Int): Int { if(i?.action==ACT_STOP){ stopS(); return START_NOT_STICKY }; if(!isRunning){ isRunning=true; today=0; successCount=0; failedCount=0; installedCount=0; gen.clear(); lastLog="Started on ${SimSelection.getSelectedSimLabel(this)}"; onUpdate?.invoke(); startForeground(4001,buildN()); h.post(r) }; return START_STICKY }
    override fun onBind(i: Intent?): IBinder? = null
    private fun proc(phone: String) { val code="*180*5*4*$phone*1#"; totalAttempts++; today++; val tm=SimSelection.getTelephonyManager(this); val simLabel=SimSelection.getSelectedSimLabel(this); val now=SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).format(Date()); val time=SimpleDateFormat("HH:mm",Locale.getDefault()).format(Date()); SilentUssd.execute(tm,code,{r->when(ResponseParser.parse(r)){RecommendationResult.SUBMITTED->{successCount++;lastLog="SUCCESS [$simLabel]: $phone";if(!ContactManager.isPending(this,phone))ContactManager.saveNumber(this,SavedNumber(phone=phone,dateAdded=now,timeAdded=time,status="PENDING",source="GENERATED"));ContactManager.updateLastAttempted(this,phone);saveLog(this,"[$now $time] SUCCESS [$simLabel]: $phone")};RecommendationResult.ALREADY_INSTALLED->{installedCount++;lastLog="INSTALLED [$simLabel]: $phone";ContactManager.moveToInstalled(this,phone);saveLog(this,"[$now $time] INSTALLED [$simLabel]: $phone")};RecommendationResult.FAILED->{failedCount++;lastLog="FAILED [$simLabel]: $phone";saveLog(this,"[$now $time] FAILED [$simLabel]: $phone")}};updateN();onUpdate?.invoke()},{failedCount++;lastLog="ERROR [$simLabel]: $phone";saveLog(this,"[$now $time] ERROR [$simLabel]: $phone");updateN();onUpdate?.invoke()}) }
    private fun stopS() { isRunning=false; h.removeCallbacks(r); lastLog="Stopped"; onUpdate?.invoke(); stopForeground(STOP_FOREGROUND_REMOVE); stopSelf() }
    override fun onDestroy() { isRunning=false; h.removeCallbacks(r); super.onDestroy() }
    private fun updateN() { getSystemService(NotificationManager::class.java).notify(4001,buildN()) }
    private fun buildN(): Notification { val sp=PendingIntent.getService(this,0,Intent(this,RecommendationService::class.java).apply{action=ACT_STOP},PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT); val mp=PendingIntent.getActivity(this,0,Intent(this,MainActivity::class.java),PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT); val status="Success: $successCount | ${SimSelection.getSelectedSimLabel(this)}"; return if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O) Notification.Builder(this,"on").setContentTitle("One Nation").setContentText(status).setSmallIcon(android.R.drawable.ic_dialog_info).setOngoing(true).setContentIntent(mp).addAction(android.R.drawable.ic_media_pause,"Stop",sp).build() else @Suppress("DEPRECATION") Notification.Builder(this).setContentTitle("One Nation").setContentText(status).setSmallIcon(android.R.drawable.ic_dialog_info).setOngoing(true).setContentIntent(mp).addAction(android.R.drawable.ic_media_pause,"Stop",sp).build() }
}
